version: "3"

services:
  server:
    build: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    ports:
      - 3306:3306
    networks:
      - net

  http-server:
    build:
      context: .
      dockerfile: ./Dockerfile_go
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=maze_db_server_1
    ports:
      - 8000:8000
    networks: 
      - net
  
networks:
  net:
    driver: bridge